### ISSUE TITLE
Consistency on loading json files

### ISSUE THREAD

**Issue by c-martinez** [TNOCS/csWeb#162]
Is there any preference for which way to load json files ?

Browsing through the code I can see some times the angular way is used:
```
$http.get(...)
```
sometimes the JQuery style:
```
$.getJSON(...)
```
and even some times d3 style:
```
d3.json(...)
```

So the question is, which style is preferred? And would it be useful trying to update existing code to be consistent? I would say sticking to the angular style might make things easier for writing tests. But of course this is a matter of choice.

Any thoughts?

**Comment by erikvullings** [comment]
Sorry for the late response - holidays and too many emails are to blame.
 
I agree, this is ugly, and using the angular way would be preferable as the others might not always be required (it would be interesting to see if the jQuery light version in angular is sufficient for our purposes, so we don't have to load jQuery). Assuming, of course, that their performance is comparable. That may be good to test first...

Happy to accept any pull requests for this... ;-)

Sent from my Windows Phone

-----Original Message-----

**Comment by c-martinez** [comment]
Just a heads up,  $http is changing on the latest version of angular:

https://docs.angularjs.org/api/ng/service/$http

Something to take into account for this issue.
