### ISSUE TITLE
Set layer opacity

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#165]
Contours that overlap cause the colors to fuse. Make the colors opaque and set the layer opacity.

http://stackoverflow.com/questions/15917031/how-to-update-opacity-of-wms-layer-in-leaflet

**Comment by damylen** [comment]
I have this working now, but now the way I would like. As far as I can see, grouplayers in leaflet don't support a layer opacity, so you need to calculate this for each feature. Hopefully leaflet 1 (in beta) will have more group/layer capabilities.
