### ISSUE TITLE
Create SimulationService

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#166]
Base class

* Interface for time mgmt
* Interface for configuring the service, e.g. by receiving layers or rules
* Interface for connecting with a transport implementation, e.g. MQTT
* Methods for informing the simulation manager which layers are available (using the REST API)
* RuleEngine (?)
* StateMachineEngine (?)
* Agent implementation, e.g. EVE (?)

**Comment by c-martinez** [comment]
Perhaps something to discuss tomorrow when when we skype -- we need a similar functionality for one of the projects we are using as test case and we've already started working on implementing this feature.
