### ISSUE TITLE
Working with multiple projects

### ISSUE THREAD

**Issue by ReinierNL** [TNOCS/csWeb#17]
The projects.json file already permits multiple references to project.json files. However, only the first one is used. It'd be very useful if we can define multiple project.json file (for different applications or demos).
Apparently, implementation of this only requires a directive, plus a description in the wiki.

**Comment by erikvullings** [comment]
Actually, it is already implemented, although not yet as directive. See index.html in csMap for the implementation.

**Comment by ReinierNL** [comment]
Pardon my ignorance, but I don't see that it works.
I see code in index.html, starting at "Start project dropdown" that is probably meant to provide this functionality, but when I add a second project to my projects.json file and reload the page, all that happens is that a little (drop down like) triangle appears, which does nothing.

**Comment by ReinierNL** [comment]
This seems to be my mistake.
It now works in my csMap.
Apparently I did not have my source files up to date..
