### ISSUE TITLE
Support multi select by Ctrl-click

### ISSUE THREAD

**Issue by ReinierNL** [TNOCS/csWeb#174]
Using the mouse, clicking on shapes, one can only select one shape (feature) at a time.
It is desirable that one can also select multiple shapes, using Ctrl-click (toggle selected state of shape that is clicked).
This also requires a way to represent attribute values for multiple shapes. 
Simplest way: leave blank if the values are not all equal. 
Less simple but more useful if the values are numbers: show statistics (min, max, sum, average).

**Comment by erikvullings** [comment]
Better option is to support three modes of operation for merging attribute values:
- ignore
- sum (default for numbers)
- scale (needs additional attribute in property type, scaleProperty). The scale property will first sum the attribute * scaleProperty, and finally divide it by the value of the summed scaleProperty. An example for population density. You sum the density * area, and finally divide it by the summed area. 

This should cover it most immediate needs.

One other thing: If we are going to use CTRL -click, we should also cover the command key on the Mac.

Alternatively, or rather additionally, we might also have a toggle to indicate add to selection, which is important for tablet and phone users.

**Comment by ReinierNL** [comment]
What to do with the representation of the attribute values is a discussion that does not belong to this issue.
This issue is about *multi select*. Also applicable e.g. when editing.

I am copying Erik's comment to issue #173
