### ISSUE TITLE
Link to website doesn't work

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#208]
On Windows 10, Excel 2013, clicking the project link only keeps the host:port, but trims the projectid.

**Comment by erikvullings** [comment]
This is probably a Chrome issue (which is my default browser).
See here: http://stackoverflow.com/questions/17656083/excel-hyperlink-to-web-page-location-with-id-or-named-anchor

**Comment by rinzeb** [comment]
Html5mode is enabled, which does not require a hash (#) in the link anymore. IE < 9 is not supported!!
