### ISSUE TITLE
icons on property mousover don't display properly

### ISSUE THREAD

**Issue by Naisunev** [TNOCS/csWeb#216]
When there is a scrollbar the icons on mouseover are offset incorrectly and actually display below the hovered area.
![image](https://cloud.githubusercontent.com/assets/2182329/10138254/f0d5508a-65fd-11e5-80b9-10a9f5804903.png)

**Comment by rinzeb** [comment]
Fixed. However, it required a change of icon. The filter and cog icon already were FontAwesome icons, but the style icon was image-based. As both types would not align nicely, I opted to replace the style icon by a FontAwesome paint-brush icon for now.
