### ISSUE TITLE
Support for different URL texts

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/csWeb#221]
In excel2map, only the url link can be defined, the url text in the FeatureProps will be the same. For long links it is often desired to have an url text other than the link, e.g. 'Show page'.

**Comment by erikvullings** [comment]
Can't you use the bbcode type for this?

**Comment by rinzeb** [comment]
The MapLayerFactory already uses bbcode for url's. However, they get converted using: 
[url=' + p[name] + ']' + p[name] + '[/url]
so the text is always the same as the link. 
Would (ab)using the StringFormat for the link text be a good solution?
[url=' + p[name] + ']' + p[stringformat] + '[/url]

**Comment by erikvullings** [comment]
If it works, why not :-)
