### ISSUE TITLE
Cell content causing errors

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#222]
When a cell contains a soft return (alt-return), the parsing goes well, but the node part returns a parse error (error code 400). Handle these.

When a cell contains an undefined value #NAME? it causes a MACRO error. Ignore these errors and consider the cells as blank.

When a cell contains a ", replace it with '..

**Comment by rinzeb** [comment]
Fixed those 3 in https://github.com/TNOCS/excel2map/commit/2fa6a49b6f634e788c59c5567494fabc36462705
