### ISSUE TITLE
Excel2map: cannot deal with hard returns in data

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#244]
When a cell contains a hard return, the corresponding json contains it too and the json-bodyparser will crash.
Besides fixing this issue, save the json in a text file, so we can more easily debug the generated layer.json.

**Comment by rinzeb** [comment]
Debugging the generated json is already implemented in the Excel2map templates. In the Helpers sheet, there is a parameter "Debug" which is set to zero. Setting it to 1 will save the generated layer.json on your harddrive.

**Comment by erikvullings** [comment]
Ah yes, good point about the debug option.

Where is the layer.json file saved?

**Comment by rinzeb** [comment]
In the current directory (obtained in vba by `cd = fs.GetAbsolutePathName(".")`). Additionally, a popup window will tell you the location where the debug file was saved.
