### ISSUE TITLE
Push notification

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#246]
It would be nice if a (simulation) service could push a notification message to the web client, e.g. how many hospitals have failed.

**Comment by damylen** [comment]
Do you want the notification to be triggered on an application level, or should it be associated to a specific layer or user?

**Comment by erikvullings** [comment]
Most likely, both.
For example, the hazardous object layer contains so many objects, that the information becomes meaningless. We could use a key, eg telling that x objects have been flooded or have no more power, but an additional notification would be useful too. Even if the layer hasn't been loaded.

Another example are events (drone has started, train is turned off, etc).

Layer notifications are useful too, so we can be more specific than ' the layer gas been updated'.
