### ISSUE TITLE
Merge templates in Excel2map

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/csWeb#255]
Some templates are almost identical, e.g. Provincie_op_naam & Provincie_op_code. 

The reason is that the Maplayerfactory matches the polygon using the 'Name' property, which contains respectively the name or code of the area (in this case the province). 

Better would be to don't search using the hardcoded 'Name' property, but define a propertyname instead. In that way, only one template is needed, which can be searched for both names and codes.

**Comment by erikvullings** [comment]
Actually, this would allow you to match any property.
