### ISSUE TITLE
Event mgmt support: Agenda widget

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#334]
During an event, it is practical if we can easily display the events that will occur in the next x hours.

Implementation:
Based on a GeoJSON layer, scan it and find all agenda items, filter them (e.g. next 2 hours), and display them in a list. When moving in time, update the agenda accordingly. When a new item is added to the layer, check if we need to include it in the agenda. 

As an agenda item may or may not be related to a location on the map, and may be represented with different feature types, we probably need to include a specific property such as isAgendaItem true|false.

**Comment by damylen** [comment]
or use the same filter/tagging approach as the kanban board. you can also look for features that have a property with 'date' type
