### ISSUE TITLE
Add image overlay property type

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#392]
Use the following properties to specify the overlay:
- imageBounds
- opacity
- attribution

**Comment by damylen** [comment]
do you mean drawingMode (featuretype-style)?

**Comment by erikvullings** [comment]
Example of a geojson layer that displays an image on the map. The geometry contains the image's bounding box (south-west, north-east), and the `geometry.type` is `Overlay`. The `properties.imageUrl` contains the link to the image path, and you can optionally specify the image's attribution and opacity.

```json
{
	"type": "FeatureCollection",
	"features": [
		{
			"type": "Feature",
            "geometry": {
                "type": "Overlay",
                "coordinates": [[52.076051, 4.303200], [52.085646, 4.326134]] 
            },
			"properties": {
                "imageUrl": "images/LT20366 LIL16 plattegronden - transparent.png",
                "attribution": "Organisator van The Life I Live.",
                "opacity": 1
            }
        }
    ]
}
```
