### ISSUE TITLE
3D view not working

### ISSUE THREAD

**Issue by erikvullings** [TNOCS/csWeb#44]
Lots of files are missing, cannot switch back to 2D (layer isn't loaded anymore).

**Comment by damylen** [comment]
Files are back, switch to 2d doesn't work yet

**Comment by erikvullings** [comment]
Switching works now - not as cleanly as I want too, but it works by disablling and enabling the Leaflet map, and destroying / creating the Cesium map.

Cesium files still need to be added to csWeb-example/public/js folder.
