### ISSUE TITLE
Add capability to show (Esri) grid files (asc, grd, flt)

### ISSUE THREAD

**Issue by ReinierNL** [TNOCS/csWeb#49]
Grid data is rather commonly used, also in Urban Strategy, and grid files are recognized by just about every GIS software.
So, it makes much sense to add "grid" as a new layer type.

**Comment by erikvullings** [comment]
I can open them on the client. However, performance is very poor.

**Comment by ReinierNL** [comment]
How does it work?
I mean, as a 'user' (with acces to a project.json file), how do I add such a layer?

**Comment by ReinierNL** [comment]
We need to be able to load grids that have co-ordinates in other co-ordinate systems. 
Especially / specifically: Dutch RD New aka Amersfoort (epsg 28992)
