### ISSUE TITLE
Nearby feature slows down selection

### ISSUE THREAD

**Issue by damylen** [TNOCS/csWeb#66]
Selection with a linkedfeature directive takes 2-3 sec, instead of < 1. We should speed it up or make this functionality optional (e.g. enable in featuretype)

**Comment by rinzeb** [comment]
Disabled FeatureRelations for low zoomlevels or when too many features are in view;  in
https://github.com/TNOCS/csWeb/commit/4b4c24cbb0b81a6e2bc7a7789b785e7097d3d9f7
