### ISSUE TITLE
Region of interest filter

### ISSUE THREAD

**Issue by rinzeb** [TNOCS/csWeb#77]
Option to specifiy a region of interest, and only show features within that area

**Comment by damylen** [comment]
How do you imagine we are going to specify the region? Based on current extent? Polygon? Distance?

-----Original Message-----

**Comment by erikvullings** [comment]
Current extent is the easiest. Maybe later,e can draw a region or select an existing area.

Sent from my Windows Phone

-----Original Message-----

**Comment by damylen** [comment]
Would be nice if you could select a polygon from a layer like a province or city

-----Original Message-----

**Comment by rinzeb** [comment]
Implemented: https://github.com/TNOCS/csWeb/commit/960bb8bf23251cba8991eb37f38acc880b4262d9
