### ISSUE TITLE
Cannot activate style (legend) for string/text attributes

### ISSUE THREAD

**Issue by ReinierNL** [TNOCS/csWeb#97]
Attributes that have string values, don't get a style icon (in the attribute list).
When such an attribute has a legend in its propertyTypeData, it can not be activated.
See the image below:
I could activate the legend for the Typecode, but NOT the one for Heating system type.

![image](https://cloud.githubusercontent.com/assets/11029099/7921595/e2439586-08a6-11e5-8656-d7b33c733070.png)

**Comment by erikvullings** [comment]
In case of using a property type of text, you could try to use the 'options' type, as they can be styled. Basically, you just add an array of values in the property type's options, and the property itself is the index in the array. As a side effect, it is more efficient wrt memory consumption, and you only need to define it once.

**Comment by ReinierNL** [comment]
Erik (or anyone else), can you describe in just a bit more detail than above, how this can be accomplished?
I've already understood that when I enter 

    "type": "options"

as a field in a propertyTypeData entry, the styling icon shows up.

Now I would also like to enter the list of possible values.
How do I do that? (for example, I have the options "A", "B" .. "G"  (for the attribute "energy label").

**Comment by erikvullings** [comment]
You just use the options property to specify them, e.g. 

```
{
                "label": "WK_CODE",
                "type": "options",
                "options": ["WK011400", "WK011401", "WK011402", "WK011403", "WK011404", "WK011405", "WK011406", "WK011407", "WK011408", "WK011409", "WK011410", "WK011411", "WK011412", "WK011413", "WK011421", "WK011432"],
                "title": "WK CODE",
                "section": "Wijk info",
                "visibleInCallOut": true,
                "canEdit": false,
                "isSearchable": false
}
```
